### ISSUE TITLE
XCode 12.0 : Property with 'retain (or strong)' attribute must be of object type `Rtt_AppleInputDeviceManager.mm`

### ISSUE THREAD

**Issue by Larpoux** [coronalabs/corona#147]
When I tried to build the target `rttplayer`  from `corona/platform/mac/ratatouille.xcodproj` I have this error: 

<img width="1364" alt="Screenshot 2020-09-08 at 19 56 14" src="https://user-images.githubusercontent.com/45900255/92511513-b269db80-f20d-11ea-8661-cc684c9c1f85.png">

I tried with releases 3601 and 3614, with same result.

**Comment by Larpoux** [comment]
Note : I had to upgrade recently XCode to Version 12.0 Beta 6
This could be the reason of my problem, because it used to work correctely two month ago.

**Comment by Larpoux** [comment]
OK, guys and girls : 
I confirm that there is problems with XCode 12.0 (I have no problems when I downgrade to XCode 11.7).

**Comment by Larpoux** [comment]
I have another problem with XCode 12.0, but I am not sure if I must feel another PR (Problem Report) : 
When I try to build my App, I have the following error during the Link Edit : 

<img width="2416" alt="Screenshot 2020-09-09 at 08 46 54" src="https://user-images.githubusercontent.com/45900255/92564180-0cec5180-f279-11ea-99fe-dc4e6a845cf8.png">

Again, there is not any problem when I downgrade XCode to version 11.7.
Unfortunately I do not know very well XCode to be more helpful.

**Comment by XeduR** [comment]
This issue has probably been addressed with https://github.com/coronalabs/corona/commit/58848d7b2545eb2278aedca5e6dba23170732967

**Comment by Shchvova** [comment]
It wasn’t. Release Xcode 12 is building against Xcode 10.15 sdk. Beta - 11.0. Still an issue for next Xcode update and Apple silicone
