### ISSUE TITLE
plugin.unityads.v4

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#368]
There seems to be an issue on device.  

**This fails**
  1. Load an app and the plugin works as expected
  2. Terminate the app using the back button
  3. Reload the app and the event listeners do not function

**But this works**
  1. Load an app and the plugin works as expected  
  2. Terminate the app using the back button
  3. Kill the process using task manager
  4. Reload the app and the event listeners do function

Doing live builds also fails (without killing the process) in between each automatic refresh.

**Comment by scottrules44** [comment]
Unity has made significant changes in V4.  Is there a particular event.phase you are expecting? Like calling .load, hitting the back button to close the app, reopening, and expecting event.phase "loaded"?

**Comment by mark-sgs** [comment]
For a start, there is no callback in response to calling `unityads.init()`

**Comment by scottrules44** [comment]
There was an issue if you call .init() and close the app(via the back button) before the init event on Android you won't get a callback when you reopen.

This should be fixed now with a recent update. 

As a note, the legacy Unity plugin triggers an event.phase == "init" right after .init() is called. Versus with v4 which may happen a little later and init could actually return an error. Will put a note in the Documentation

**Comment by mark-sgs** [comment]
Still broken for me.  Plugin reports - plugin.unityads.v4: 1.0.0 (SDK: 4.0.1)

1. load app and init() calls the event listener, which calls .load() and an ad is available.
2. watch the ad and another is downloaded and ready to view, close app with back button.
3. on reload init() does NOT call the event listener and no ads work.

**Comment by mark-sgs** [comment]
OK I rebuilt and now this works.  I wasn't closing the game before init completed.  But either way the fix has fixed my problem thanks.
